### ISSUE TITLE
Size of generated JS

### ISSUE THREAD

**Issue by elliott5** [go-kivik/pouchdb#19]
You're doing great work, thank you!

I'm currently writing a Kivik driver for https://github.com/cayleygraph/cayley see: https://github.com/dennwc/cayley/pull/4 

Currently the tests all pass, but there is still work to do to make it practical to use. One of the issues I have come up against is the size of the generated JS.

To get the size of the generated JS for Cayley down to a reasonable level I had to remove the "net" dependency from the UUID library. Because "net" it is not used in the browser, it is redundant code. But using the "net" library inflates the size of the transpiled JS code by 673k bytes. You can see my PR to do this here: https://github.com/pborman/uuid/pull/40

I believe the same issue exists for go-kivik/pouchdb and indeed for the main kivik repo, since it uses "net/http" which uses "net". 

https://github.com/gopherjs/gopherjs/wiki/JavaScript-Tips-and-Gotchas says:
> For making HTTP requests, don't use net/http, as importing this will also compile-in the entire TLS stack! Use GopherJS bindings to XmlHTTPRequest instead. For code that'll be compiled either to Go or JS, use a function that's constrained by build tags, so in JS it uses XHR and in Go it uses net/http.

I appreciate this is a pretty major change for both repos, which is why I have not simply raised a PR for this one to replace the reference to ```http.StatusNotFound``` in pouchdb.go with a local version of the constant, but rather chosen to raise this discussion issue.

**Comment by flimzy** [comment]
Thank you for bringing this to my attention!

The `http.Status*` variables should be very easy to replace--the relevant ones are already constants in the `kivik` package.  Any remaining ones are simply an oversight on my part.  I can fix that immediately (see #20).

I'm sure that won't be enough, because kivik also depends on the `net/http` library. Removing those references wont' be nearly so easy.  But it should be done, if possible.

**Comment by elliott5** [comment]
Well done for acting so promptly!

You may find the following helpful...

To find the size of the generated (minified) JS for each package on my mac, I use the following:
```
echo "STANDARD"

go list -tags 'js' -f '{{join .Deps "\n"}}' | xargs go list -tags 'js' -f '{{if .Standard}}{{.Target}}{{end}}' | grep . | sed 's/\/usr\/local/\/Users\/elliott/' | sed 's/darwin_amd64/darwin_js_min/' | xargs ls -l | sort

echo "NOT STANDARD"

go list -tags 'js' -f '{{join .Deps "\n"}}' |  xargs go list -tags 'js' -f '{{if not .Standard}}{{.Target}}{{end}}' | grep . | sed 's/darwin_amd64/darwin_js_min/' | xargs ls -l | sort
```

**Comment by flimzy** [comment]
Thanks for the shell tips.  That is helpful.  I see that `net/http` is still being pulled in (no surprise).

One place I see that being pulled in is in `kivik/errors`, just for the benefit of `http.StatusText`: https://github.com/flimzy/kivik/blob/master/errors/errors.go#L31

That should be easy functionality to move into the kivik library, or possibly even omit entirely.  I'll try to work on that soon, possibly today. In the meantime, if you see any other places where `net/http` is being used, feel free to leave a comment, or even submit a PR to remove it, if the solution is obvious enough.

**Comment by flimzy** [comment]
Update, it looks like `kivik/errors` is the last place depending on `net/http`:
![pouchdb](https://user-images.githubusercontent.com/8555063/33761449-5640f572-dc09-11e7-83c3-6270dddc86cc.png)

**Comment by elliott5** [comment]
Great work!

You'll just need to decide if you want to remove that functionality from all targets; or use build tags and two little stub go files to provide the functionality to !js targets only.

**Comment by elliott5** [comment]
...but what you've done is better - keep all the functionality by moving it into the package!

**Comment by flimzy** [comment]
> ..but what you've done is better - keep all the functionality by moving it into the package!

Indeed. It even improves functionality marginally, by only responding to statuses that are used by CouchDB/Kivik. :)

**Comment by flimzy** [comment]
I believe `net/http` has now been successfully purged from the `go-kivik/pouchdb` dependency tree:

![pouchdb2](https://user-images.githubusercontent.com/8555063/33766623-aa9ca1a6-dc1e-11e7-99a9-9526d106100e.png)

Is there anything else you think should be addressed before closing this issue?

**Comment by elliott5** [comment]
LGTM, so please close this issue.
I’m not going to be able to run any tests until next week, so I’ll let you know if I find any new issue then.
Thank you for your prompt response to this issue!
